<<<<<<< HEAD
# Generated by Django 6.0.6 on 2026-06-06 14:27
=======
# Generated by Django 6.0.6 on 2026-06-07 06:25
>>>>>>> c8d20076756ab9c031d2e122eda2829450b099c8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
<<<<<<< HEAD
            field=models.CharField(choices=[('USER', 'User'), ('EMPLOYEE', 'Employee'), ('ADMIN', 'Admin')], default='USER', max_length=50),
=======
            field=models.CharField(choices=[('USER', 'User'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='USER', max_length=20),
>>>>>>> c8d20076756ab9c031d2e122eda2829450b099c8
        ),
    ]
