# Generated by Django 6.0.6 on 2026-06-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmend_id', models.CharField(editable=False, help_text='Appointment ID', max_length=16, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('CLEANING', 'Cleaning'), ('REPAIR', 'Repair'), ('HOME_SERVICES', 'Home Services')], max_length=100)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('DIAGNOSING', 'Diagnosing the problem'), ('REPAIRING', 'Repairing the problem'), ('PICKUP', 'Ready for pickup')], max_length=50)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('PAYMENT_PENDING', 'Payment Pending')], default='PAYMENT_PENDING', max_length=50)),
                ('date', models.DateTimeField(help_text='the appointmend date', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
