# Generated by Django 6.0.6 on 2026-06-07 12:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('CLEANING', 'Cleaning'), ('REPAIR', 'Repair'), ('HOME_SERVICES', 'Home Services')], max_length=100)),
                ('address', models.TextField(blank=True)),
                ('issue', models.TextField()),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('PAYMENT_PENDING', 'Payment Pending'), ('PARTIAL', 'Partial')], default='PAYMENT_PENDING', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('RECEIVE', 'Item has been received'), ('DIAGNOSING', 'Diagnosing the problem'), ('REPAIRING', 'Repairing the problem'), ('PICKUP', 'Ready for pickup'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50)),
                ('rejection_reason', models.TextField(blank=True)),
                ('date', models.DateTimeField(help_text='the appointment date', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RepairLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(blank=True, help_text='e.g. Laptop, Desktop, Phone', max_length=100)),
                ('findings', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('quoted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status_at_time', models.CharField(help_text='Snapshot of appointment status when logged', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
