# Generated by Django 6.0.6 on 2026-06-06 14:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cca17245-4cf0-41ed-acfb-2a7ca834d48e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
