# Generated by Django 6.0.6 on 2026-06-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('DIAGNOSING', 'Diagnosing the problem'), ('REPAIRING', 'Repairing the problem'), ('PICKUP', 'Ready for pickup')], default='ACCEPTED', max_length=50),
        ),
    ]
