# Generated by Django 6.0.6 on 2026-06-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmend_id',
            field=models.CharField(editable=False, help_text='Appointment ID', max_length=32, primary_key=True, serialize=False),
        ),
    ]
