# Generated by Django 6.0.6 on 2026-06-06 06:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_appointment_appointmend_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmend_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
