# Generated by Django 6.0.6 on 2026-06-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_service_alter_appointment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('CLEANING', 'Cleaning'), ('REPAIR', 'Repair'), ('HOME_SERVICES', 'Home Services')], max_length=100),
        ),
    ]
