# Generated by Django 6.0.6 on 2026-06-06 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_appointment_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
