# Generated by Django 6.0.6 on 2026-06-06 06:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_appointment_assigned_staff_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('DIAGNOSING', 'Diagnosing the problem'), ('REPAIRING', 'Repairing the problem'), ('PICKUP', 'Ready for pickup'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ab5feb04-95bc-4407-9952-fa2b76aa5a08'), editable=False, primary_key=True, serialize=False),
        ),
    ]
