# Generated by Django 6.0.6 on 2026-06-06 07:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_notification_id_alter_repairlog_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('408743ea-9ed2-412b-99db-285c16914d1a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
