# Generated by Django 6.0.6 on 2026-06-06 09:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_alter_notification_id_alter_repairlog_quoted_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bd0f4189-498d-4281-8678-cf255560b84e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
