# Generated by Django 6.0.6 on 2026-06-06 10:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_alter_notification_id_alter_repairlog_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='description',
            new_name='issue',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(help_text='the appointment date', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d29d94ef-4067-4661-8db4-0049c78cc2a2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
