# Generated by Django 6.0.6 on 2026-06-06 10:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_rename_description_appointment_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('RECEIVE', 'Item has been received'), ('DIAGNOSING', 'Diagnosing the problem'), ('REPAIRING', 'Repairing the problem'), ('PICKUP', 'Ready for pickup'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f9b5dd1-f14a-4407-890e-636332bebad1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='repairlog',
            name='appointment',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='booking.appointment'),
        ),
    ]
